# Generated by Django 4.2.10 on 2024-02-17 18:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Proveedor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=254, verbose_name='Nombre')),
                ('apellido', models.CharField(max_length=254, verbose_name='Apellido')),
                ('direccion', models.CharField(max_length=254, verbose_name='Dirección')),
                ('tipo', models.CharField(choices=[('vendedores', 'Vendedores'), ('compradores', 'Compradores')], default='vendedores', max_length=25, verbose_name='Tipo')),
                ('ciudad', models.CharField(max_length=150, verbose_name='Ciudad')),
                ('longitud', models.FloatField()),
                ('latitud', models.FloatField()),
                ('estado_geo', models.BooleanField(default=False)),
                ('cargo', models.CharField(choices=[('asesor', 'Asesor'), ('cajero', 'Cajero')], default='asesor', max_length=25, verbose_name='Cargo')),
            ],
            options={
                'verbose_name': 'Proveedor',
                'verbose_name_plural': 'Proveedores',
            },
        ),
    ]
