# Generated by Django 4.2.10 on 2024-02-17 18:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Proveedor',
            new_name='Usuarios',
        ),
    ]
