# Generated by Django 4.2.10 on 2024-02-17 21:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0003_alter_usuarios_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuarios',
            name='tipo',
            field=models.CharField(choices=[('vendedor', 'Vendedor'), ('comprador', 'Comprador')], default='vendedor', max_length=25, verbose_name='Tipo'),
        ),
    ]
