# Generated by Django 4.2.10 on 2024-02-17 21:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0004_alter_usuarios_tipo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuarios',
            name='cargo',
            field=models.CharField(blank=True, choices=[('asesor', 'Asesor'), ('cajero', 'Cajero')], max_length=25, null=True, verbose_name='Cargo'),
        ),
    ]
