# Generated by Django 4.2.10 on 2024-02-17 22:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0005_alter_usuarios_cargo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuarios',
            name='direccion',
            field=models.CharField(blank=True, max_length=254, null=True, verbose_name='Dirección'),
        ),
    ]
