# Generated by Django 4.2.10 on 2024-02-17 23:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0008_alter_usuarios_direccion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuarios',
            name='latitud',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='usuarios',
            name='longitud',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
